version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog/Dockerfile
volumes:
  mongo_data:
